name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: ./docker/build_image.sh

      # - name: Build the Docker image
      #   run: |
      #     ls -a
      #     echo ""
      #     uname -a

# - uses: actions/checkout@v4
# - name: Build the Docker image
#   run: ./docker/build_image.sh
